---
crate-directory: crate1
title: "Phase Field Simulation: Homogeneous Nucleation Benchmark No.8a"
description: "An example of generating an ro-crate from a PFHub result, for now this is only focused on the computational platform, environment and implementation"
contexts:
  - "https://w3id.org/ro/terms/workflow-run/context"
authors:
  - name: Daniel Wheeler
    orcid: https://orcid.org/0000-0002-2653-7418
    affiliation: NIST
  - name: Austyn Nguyen
    orcid: https://orcid.org/0009-0008-2880-8403
    affiliation: NIST
license:
  identifier: "https://spdx.org/licenses/NIST-PD.html"
  name: "NIST-PD"
  description: "NIST Public Domain Notice"
  url: https://github.com/tcheneau/simpleRPL/blob/e645e69e38dd4e3ccfeceb2db8cba05b7c2e0cd3/LICENSE.txt
outputs:
  - path: "data/stats.txt"
    type: file
    encodingFormat: "text/tab-separated-values"
    description: "Solid Fraction and Free Energy vs. Time"
    name: stats.txt
    columns:
      - identifier: time
        description: "Simulation time"
        unit: s
        type: float
      - identifier: fraction
        description: "Solid fraction"
        unit: null
        type: float
      - identifier: energy
        description: "Free energy"
        type: float
        unit: J
  - path: "./data/fields"
    type: directory
    encodingFormat: application/tar+gzip
    description: "The phase field variable at various times during the simulation"
    name: "t=X.Y.tar.gz"
    columns:
      - identifier: phaseField
        description: "Phase field variable"
        unit: null
        type: float
inputs:
  - path: "../benchmark8/params8a.yaml"
    encodingFormat: "text/yaml"
    name: params8a.yaml
    description: "Parameter file require to run simulation"
    download: false
    columns:
      - identifier: factor
        description: "Fraction of equilibrium radius"
        unit: null
        type: float
        value: 1.1
  - path: "https://github.com/wd15/phase-field-nucleation-benchmark/blob/master/fipy/benchmark8a.py"
    download: true
    encodingFormat: text/x-script.python
    name: benchmark8a.py
    description: "script to run the main simulation"
  - path: "../pyproject.toml"
    name: pyproject.toml
    encodingFormat: application/toml
    description: "File required to build Python environment using Poetry"
    download: false
workflow:
  dateCreated: "2017-01-09"
  name: "Main workflow"
  creator: https://orcid.org/0000-0002-2653-7418
  description: "python benchmark8a.py params8a.yaml"
  agent: https://orcid.org/0009-0008-2880-8403
implementation:
  identifier: "https://github.com/wd15/phase-field-nucleation-benchmark/commit/2a7e1778cd2f4988b592f2bd0c84852911111fb7"
  programmingLanguage: "Python 3.11"
  description: "FiPy implementation for \"Phase Field Benchmark Problems for Nucleation\""
  name: phase-field-nucleation-benchmark
  applicationCategory: Script
  codeRepository: https://github.com/wd15/phase-field-nucleation-benchmark
  softwareHelp: https://github.com/wd15/phase-field-nucleation-benchmark/blob/master/README.md
dependencies:
  - name: FiPy
    identifier: "#fipy"
    version: 3.4.4
    description: "FiPy is a Finite Volume PDE solver written in Python"
    url: https://github.com/usnistgov/fipy
  - name: Numpy
    identifier: "#numpy"
    version: 1.26.4
    description: "Numpy library"
    url: https://github.com/numpy/numpy
  - name: Scipy
    identifier: "#scipy"
    description: "Scipy library"
    version: 1.13.1
    url: https://github.com/scipy/scipy


    
      
      
    
    

    
    
  

  

  
